@host = http://localhost:5127
@imoNumber = 0010005
POST {{host}}/ships/{{imoNumber}}/passengers
Content-Type: application/json

{
  "passengers": [
    "John Doe",
    "Jane Smith"
  ]
}

// Expected response for the first request:
# HTTP/1.1 400 Bad Request
# {
#   ...
#   "status": 400,
#   "errors": {
#     "Ship.NotFound": [
#       "Could not find a ship with the given IMO number."
#     ]
#   },
#   ...
# }
