@host = http://localhost:5127
POST {{host}}/ships/passenger
Content-Type: application/json

{
  "imoNumber": "12abc67",
  "name": "Titanic",
  "length": 50,
  "width": 10
}

// Expected response:
# HTTP/1.1 400 Bad Request

# {
#   ...
#   "title": "One or more validation errors occurred.",
#   "status": 400,
#   "errors": {
#     "Ship.InvalidImoFormat": [
#       "The IMO number must be 7 characters long and contain only digits."
#     ]
#   },
#   ...
# },
