@host = http://localhost:5127
POST {{host}}/ships
Content-Type: application/json

{
  "shipType": "Passenger",
  "imoNumber": "0000007",
  "name": "Titanic",
  "length": 50,
  "width": 10
}

// Expected response:
# HTTP/1.1 400 Bad Request

# {
#   ...
#   "title": "One or more validation errors occurred.",
#   "status": 400,
#   "errors": {
#     "ImoNumber.InvalidChecksum": [
#       "The provided IMO number has invalid checksum."
#     ]
#   },
#   ...
# },
