@host = http://localhost:5127
POST {{host}}/ships
Content-Type: application/json

{
  "shipType": "Tanker",
  "imoNumber": "0000000",
  "name": "Titanic",
  "length": 50,
  "width": 10,
  "tanks": [
    {
      "fuelType": "Diesel",
      "capacity": 1000
    },
    {
      "fuelType": "HeavyFuel",
      "capacity": 2000
    },
    {
      "fuelType": "Diesel",
      "capacity": 3000.245
    }
  ]
}

// Expected response for the first request:
# HTTP/1.1 200 OK

# {
#   "imoNumber": "0000000",
#   "name": "Titanic",
# }

// Expected response for any subsequent request with the same IMO number:
# HTTP/1.1 409 Conflict

# {
#  ...
#  "title": "A ship with this IMO number already exists.",
#  "status": 409,
#  ...
# }